apiVersion: apps/v1

kind: Deployment

metadata:
  #name: result-app
  name: service-result-jules
  namespace: global-vote-app

spec:
  # replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        #image: result-app ==> Besoin de chercher l'image sur GCP
        # On met donc l'adresse pour aller trouver l'image déjà crée
        image: gcr.io/cellular-axon-325108/result-jr:latest
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 4000
