apiVersion: apps/v1

kind: Deployment

metadata:
#   name: worker-app
    namespace: global-vote-app
    name: service-worker-jules

spec:
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        #image: worker-app
        image: gcr.io/cellular-axon-325108/worker-jr:latest
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            # test sur valeur cpu
            cpu: "500m"

